# Generated by Django 5.2.17 on 2026-10-08 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_order_payment_method_alter_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='نام')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='تلفن')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ نسیه')),
                ('remaining_amount', models.PositiveBigIntegerField(verbose_name='مانده')),
                ('status', models.CharField(choices=[('open', 'باز'), ('settled', 'تسویه\u200cشده'), ('refunded', 'برگشت\u200cخورده')], db_index=True, default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='orders.order')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='credits.debtor')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ')),
                ('account', models.CharField(choices=[('cash', 'صندوق (نقد)'), ('bank', 'بانک / کارت')], default='cash', max_length=5)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='credits.credit')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('idempotency_key', 'credit'), name='uniq_credit_payment_idem'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='credit_payment_amount_gt_zero')],
            },
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.UniqueConstraint(fields=('order',), name='uniq_credit_per_order'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_amount__lte', models.F('amount'))), name='credit_remaining_lte_amount'),
        ),
    ]
