# Generated by Django 5.2.17 on 2026-09-28 11:38

import django.db.models.deletion
import tables.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('empty', 'خالی'), ('active', 'فعال'), ('reserved', 'رزرو شده')], db_index=True, default='empty', max_length=10)),
                ('public_token', models.CharField(default=tables.models.new_token, editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entered_at', models.DateTimeField()),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='tables.table')),
            ],
            options={
                'ordering': ['-entered_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('exited_at__isnull', True)), fields=('table',), name='one_open_session_per_table')],
            },
        ),
    ]
