# Generated by Django 5.2.17 on 2026-09-28 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('source', models.CharField(choices=[('admin', 'ادمین'), ('customer', 'مشتری')], default='customer', max_length=10)),
                ('status', models.CharField(choices=[('new', 'ثبت شد'), ('preparing', 'در حال آماده\u200cسازی'), ('ready', 'آماده شد'), ('delivered', 'تحویل داده شد'), ('paid', 'پرداخت\u200cشده'), ('cancelled', 'لغو شده')], db_index=True, default='new', max_length=10)),
                ('payment_status', models.CharField(default='unpaid', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'نقدی'), ('card_reader', 'کارتخوان'), ('card_transfer', 'کارت\u200cبه\u200cکارت')], max_length=15, null=True)),
                ('customer_note', models.CharField(blank=True, max_length=200)),
                ('customer_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('total', models.PositiveBigIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('bar_printed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tables.tablesession')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tables.table')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=80)),
                ('unit_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('note', models.CharField(blank=True, max_length=120)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'نقدی'), ('card_reader', 'کارتخوان'), ('card_transfer', 'کارت\u200cبه\u200cکارت')], max_length=15)),
                ('amount', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order')),
            ],
        ),
    ]
