# Generated by Django 5.2.17 on 2026-10-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_payment_options_order_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', '-number']},
        ),
    ]
