# Generated by Django 5.2.17 on 2026-10-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'نقدی'), ('card_reader', 'کارتخوان'), ('card_transfer', 'کارت\u200cبه\u200cکارت'), ('credit', 'نسیه')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('card_reader', 'کارتخوان'), ('card_transfer', 'کارت\u200cبه\u200cکارت'), ('credit', 'نسیه')], max_length=15),
        ),
    ]
