# Generated by Django 5.2.17 on 2026-09-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('value', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('amount', models.PositiveBigIntegerField()),
                ('category', models.CharField(choices=[('raw_materials', 'raw_materials'), ('salary', 'salary'), ('rent', 'rent'), ('water', 'water'), ('electricity', 'electricity'), ('gas', 'gas'), ('internet', 'internet'), ('repairs', 'repairs'), ('equipment', 'equipment'), ('advertising', 'advertising'), ('transport', 'transport'), ('supplies', 'supplies'), ('other', 'other')], default='other', max_length=20)),
                ('date', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='به کافه\u200cکتاب خوش آمدید ☕📚', max_length=120, verbose_name='عنوان')),
                ('message', models.TextField(default='لحظه\u200cای برای خودتان، یک فنجان برای حالتان.', max_length=400, verbose_name='متن')),
                ('enabled', models.BooleanField(default=True, verbose_name='فعال')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
