# Generated by Django 5.2.17 on 2026-10-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='کافه\u200cکتاب', max_length=120, verbose_name='نام کافه')),
                ('address', models.TextField(blank=True, default='', max_length=400, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='شماره تماس')),
                ('receipt_note', models.TextField(blank=True, default='', max_length=150, verbose_name='یادداشت پایین رسید')),
                ('auto_print', models.BooleanField(default=True, verbose_name='چاپ خودکار سفارش بار')),
                ('low_stock_alert', models.BooleanField(default=True, verbose_name='هشدار موجودی کم در داشبورد')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
