# Generated by Django 5.2.17 on 2026-10-05 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cafesettings'),
        ('orders', '0002_alter_payment_options_order_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafesettings',
            name='opening_bank',
            field=models.PositiveBigIntegerField(default=0, verbose_name='موجودی اولیه بانک'),
        ),
        migrations.AddField(
            model_name='cafesettings',
            name='opening_cash',
            field=models.PositiveBigIntegerField(default=0, verbose_name='موجودی اولیه صندوق'),
        ),
        migrations.AddField(
            model_name='expense',
            name='account',
            field=models.CharField(choices=[('cash', 'صندوق (نقد)'), ('bank', 'بانک / کارت')], default='cash', max_length=5),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('salary', 'salary'), ('rent', 'rent'), ('water', 'water'), ('electricity', 'electricity'), ('gas', 'gas'), ('internet', 'internet'), ('repairs', 'repairs'), ('equipment', 'equipment'), ('advertising', 'advertising'), ('transport', 'transport'), ('supplies', 'supplies'), ('other', 'other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sale', 'فروش'), ('cogs', 'بهای تمام\u200cشده'), ('cogs_rev', 'برگشت بهای تمام\u200cشده'), ('purchase', 'خرید'), ('waste', 'ضایعات'), ('expense', 'هزینه'), ('refund', 'برگشت از فروش')], max_length=10)),
                ('source_type', models.CharField(max_length=20)),
                ('source_id', models.CharField(max_length=40)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('detail', models.CharField(blank=True, max_length=240)),
                ('method', models.CharField(blank=True, choices=[('cash', 'نقدی'), ('card_reader', 'کارتخوان'), ('card_transfer', 'کارت\u200cبه\u200cکارت')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='orders.order')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('cash', 'صندوق'), ('bank', 'بانک'), ('inventory', 'موجودی انبار'), ('revenue', 'درآمد فروش'), ('cogs', 'بهای تمام\u200cشده'), ('waste', 'ضایعات'), ('expense', 'هزینه\u200cهای عملیاتی')], max_length=10)),
                ('side', models.CharField(choices=[('debit', 'بدهکار'), ('credit', 'بستانکار')], max_length=6)),
                ('amount', models.PositiveBigIntegerField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.journalentry')),
            ],
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('kind', 'source_type', 'source_id'), name='uniq_journal_source'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.UniqueConstraint(fields=('entry', 'account', 'side'), name='uniq_journal_line'),
        ),
    ]
