# Generated by Django 5.2.17 on 2026-10-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_journalentry_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='kind',
            field=models.CharField(choices=[('sale', 'فروش'), ('cogs', 'بهای تمام\u200cشده'), ('cogs_rev', 'برگشت بهای تمام\u200cشده'), ('purchase', 'خرید'), ('waste', 'ضایعات'), ('expense', 'هزینه'), ('refund', 'برگشت از فروش'), ('opening_stock', 'موجودی اولیه'), ('revaluation', 'تجدید ارزش')], max_length=15),
        ),
    ]
