# Generated by Django 5.2.17 on 2026-10-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_journalentry_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False, verbose_name='باز است')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان باز شدن')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بسته شدن')),
            ],
        ),
    ]
