# Generated by Django 5.2.17 on 2026-10-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_cafestatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecuritySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "security_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="هش رمز امنیتی",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
            ],
        ),
    ]