# Generated by Django 5.2.17 on 2026-10-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_securitysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='kind',
            field=models.CharField(choices=[('sale', 'فروش'), ('cogs', 'بهای تمام\u200cشده'), ('cogs_rev', 'برگشت بهای تمام\u200cشده'), ('purchase', 'خرید'), ('waste', 'ضایعات'), ('expense', 'هزینه'), ('refund', 'برگشت از فروش'), ('opening_stock', 'موجودی اولیه'), ('revaluation', 'تجدید ارزش'), ('credit_payment', 'تسویه نسیه'), ('credit_pay_rev', 'برگشت تسویه نسیه')], max_length=15),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='method',
            field=models.CharField(blank=True, choices=[('cash', 'نقدی'), ('card_reader', 'کارتخوان'), ('card_transfer', 'کارت\u200cبه\u200cکارت'), ('credit', 'نسیه')], max_length=15),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='account',
            field=models.CharField(choices=[('cash', 'صندوق'), ('bank', 'بانک'), ('inventory', 'موجودی انبار'), ('revenue', 'درآمد فروش'), ('cogs', 'بهای تمام\u200cشده'), ('waste', 'ضایعات'), ('expense', 'هزینه\u200cهای عملیاتی'), ('receivable', 'بدهکاران (نسیه)')], max_length=10),
        ),
    ]
