# Generated by Django 5.2.17 on 2026-09-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorytransaction_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='reason',
            field=models.CharField(blank=True, choices=[('expired', 'تاریخ\u200cگذشته'), ('damaged', 'آسیب\u200cدیده'), ('spoiled', 'فاسدشده'), ('preparation_error', 'خطای آماده\u200cسازی'), ('other', 'سایر موارد')], max_length=20, null=True),
        ),
    ]
