# Generated by Django 5.2.17 on 2026-09-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorytransaction_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='item_name_snapshot',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
