# Generated by Django 5.2.17 on 2026-10-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorytransaction_item_name_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='account',
            field=models.CharField(blank=True, choices=[('cash', 'صندوق (نقد)'), ('bank', 'بانک / کارت')], default='cash', max_length=5),
        ),
    ]
