# Generated by Django 5.2.17 on 2026-10-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorytransaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='kind',
            field=models.CharField(choices=[('purchase', 'خرید'), ('waste', 'ضایعات'), ('order_consume', 'مصرف سفارش'), ('order_restore', 'بازگشت (لغو سفارش)'), ('adjust', 'اصلاح'), ('revaluation', 'تجدید ارزش')], max_length=15),
        ),
    ]
